### PR TITLE
Fix whitespace view in code

### LINKED ISSUE #2041: Template panel does not render <script> tag correctly
## Issue:
There is an issue with rendering `<script></script>` tags in the template panel. The template source incorrectly removes spaces(tabs) within the script tags, which causes the content to render incorrectly.

395896872-7a1a32bc-4a85-45c3-8497-b9fe04c561d7

## Expected Behavior:
The `<script></script>` tags should render correctly with all spaces(tabs) intact, allowing for proper functionality.

### PR DESCRIPTION
**Pull request by thesayfulla**
Fixes #2041

### CODE REVIEW

**Comment by tim-schilling** [comment]
Thank you @thesayfulla for pushing this forward. I updated your approach quite a bit. Let me know what you think. The whitespace wasn't being respected in my testing until I adjusted the `.w` class styles to use `white-space: pre-wrap`.

I took it a step further and regenerated the pygments styles so that we got to use the color highlighting too.

Screenshot 2024-12-23 at 8 32 53 AM


@matthiask I think this is how the toolbar used to do things, but I suspect some of the details were lost to time.

**Review by matthiask — APPROVED** [review]
Thanks, that's excellent!

**Comment by tim-schilling** [comment]
@thesayfulla if you're good with the result, we can merge this in.

**Comment by thesayfulla** [comment]
@tim-schilling Great job! I really liked it - let's move ahead and merge it.

**Pull request merged**
